apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod
spec:
  containers:
  - name: db
    image: docker.io/library/postgres:17.6
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: DB_NAME
    ports:
    - containerPort: 5432
      hostPort: ${DB_PORT}
    volumeMounts:
    - name: db-data
      mountPath: /var/lib/postgresql/data
  - name: redis
    image: docker.io/library/redis:8.2.1
    ports:
    - containerPort: 6379
      hostPort: ${REDIS_PORT}
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: db-data
    persistentVolumeClaim:
      claimName: db-data-pvc
  - name: redis-data
    persistentVolumeClaim:
      claimName: redis-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
